/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dataprotectionapp;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
/**
 *
 * @author Tony Clabby x16411702
 */
public class DataProtectionGUI extends javax.swing.JFrame {

    //variables
    String answer1;
    String answer2;
    String answer3;
    String answer4;
    int score;
    int count;
    
    //Array
    DataProtection myArray[] = new DataProtection[50];
    
private void groupButton( ) {

ButtonGroup bg1 = new ButtonGroup( );

bg1.add(jRadioButton1);
bg1.add(jRadioButton2);
bg1.add(jRadioButton3);

ButtonGroup bg2 = new ButtonGroup( );

bg2.add(jRadioButton4);
bg2.add(jRadioButton5);
bg2.add(jRadioButton6);

ButtonGroup bg3 = new ButtonGroup( );

bg3.add(jRadioButton7);
bg3.add(jRadioButton8);
bg3.add(jRadioButton9);

ButtonGroup bg4 = new ButtonGroup( );

bg4.add(jRadioButton10);
bg4.add(jRadioButton11);
bg4.add(jRadioButton12);
}
    
    public DataProtectionGUI() {
        initComponents();
        groupButton();
        count=0;
        score=0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        btnRadios = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        navBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jRadioButton1.setText("At any time");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("First day of a month");

        jRadioButton3.setText("Once a year");

        btnRadios.setText("Submit Answers");
        btnRadios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRadiosActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quiz");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Question 1: When are you entitled to receive your personal data?");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Question 2: If an organisation has wrong information about you....");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Question 3: What is the maximum fee for requesting access to your data?");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Question 4: If a data controller holds personal details about you for marketing purposes and you object they have to reply within?");

        jRadioButton4.setText("must wait until they contact you.");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jRadioButton5.setText("have a right to contact them and ask them to change it.");

        jRadioButton6.setText("hire a lawyer to deal with the situation");

        jRadioButton7.setText("100 Euro");

        jRadioButton8.setText("It is free");

        jRadioButton9.setText("6.35 Euro");

        jRadioButton10.setText("A week");
        jRadioButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton10ActionPerformed(evt);
            }
        });

        jRadioButton11.setText("40 Days");

        jRadioButton12.setText("A year");

        navBtn.setText("Get Score");
        navBtn.setMaximumSize(new java.awt.Dimension(109, 23));
        navBtn.setMinimumSize(new java.awt.Dimension(109, 23));
        navBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(448, 448, 448)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton6)
                    .addComponent(jRadioButton9)
                    .addComponent(jRadioButton8)
                    .addComponent(jRadioButton7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jRadioButton12)
                            .addGap(492, 492, 492))
                        .addComponent(navBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnRadios)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton11)
                    .addComponent(jRadioButton10)
                    .addComponent(jLabel5))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton3)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton6)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton9)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(btnRadios)
                .addGap(18, 18, 18)
                .addComponent(navBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void btnRadiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRadiosActionPerformed
        DataProtection myDataProtection = new DataProtection();
        
        File outFile;
        FileWriter fw;
        BufferedWriter bw;
        
        String radioTextQ1 = "";
        String radioTextQ2 = "";
        String radioTextQ3 = "";
        String radioTextQ4 = "";
        int score = 0;
        
        //Selecting output for Question 1
        if(jRadioButton1.isSelected()){
            radioTextQ1 = jRadioButton1.getText();
            answer1 = "Correct";
            score = score+1;
        }
        
        if(jRadioButton2.isSelected()){
            radioTextQ1 = jRadioButton2.getText();
            answer1 = "Wrong";
        }
        
        if(jRadioButton3.isSelected()){
            radioTextQ1 = jRadioButton3.getText();
            answer1 = "Wrong";
        }
        
        //Selecting output for Question 2
        if(jRadioButton4.isSelected()){
            radioTextQ2 = jRadioButton4.getText();
            answer2 = "Wrong";
        }
        
        if(jRadioButton5.isSelected()){
            radioTextQ2 = jRadioButton5.getText();
            answer2 = "Correct";
            score = score+1;
        }
        
        if(jRadioButton6.isSelected()){
            radioTextQ2 = jRadioButton6.getText();
            answer2 = "Wrong";
        }
        
        //Selecting output for Question 3
        if(jRadioButton7.isSelected()){
            radioTextQ3 = jRadioButton7.getText();
            answer3 = "Wrong";
        }
        
        if(jRadioButton8.isSelected()){
            radioTextQ3 = jRadioButton8.getText();
            answer3 = "Wrong";
        }
        
        if(jRadioButton9.isSelected()){
            radioTextQ3 = jRadioButton9.getText();
            answer3 = "Correct";
            score = score+1;
        }
        
        //Selecting output for Question 4
        if(jRadioButton10.isSelected()){
            radioTextQ4 = jRadioButton10.getText();
            answer4 = "Wrong";
        }
        
        if(jRadioButton11.isSelected()){
            radioTextQ4 = jRadioButton11.getText();
            answer4 = "Correct";
            score = score+1;
        }
        
        if(jRadioButton12.isSelected()){
            radioTextQ4 = jRadioButton12.getText();
            answer4 = "Wrong";
        }
        
        //Set Variables
        myDataProtection.setAnswer1(answer1);
        myDataProtection.setAnswer2(answer2);
        myDataProtection.setAnswer3(answer3);
        myDataProtection.setAnswer4(answer4);
        myDataProtection.setScore(score);
        
        //Push into the array
        myArray[count]=myDataProtection;
        count++;
        
        //Creating an instance of the file and setting up a new file
        try{
        outFile = new File("Answers.txt");
        fw = new FileWriter(outFile, true);
        bw = new BufferedWriter(fw);
        
        //Write to the file
        bw.write(radioTextQ1);
        bw.newLine();
        bw.write(radioTextQ2);
        bw.newLine();
        bw.write(radioTextQ3);
        bw.newLine();
        bw.write(radioTextQ4);
        bw.newLine();
        bw.newLine();
        
        //Close the stream
        bw.close();
        }
        //Error message in case of exception
        catch(IOException e){
            JOptionPane.showMessageDialog(null, "Error writing the file.");
        }
    }//GEN-LAST:event_btnRadiosActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void navBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navBtnActionPerformed
        
        //Loop to navigate through the array
        for(int i=0;i<count;i++){
                DataProtection myDataProtection = new DataProtection ();

                myDataProtection=myArray[i];
                
                //Output from the array
                JOptionPane.showMessageDialog(null, "Q1: "+myDataProtection.getAnswer1());
                JOptionPane.showMessageDialog(null, "Q2: "+myDataProtection.getAnswer2());
                JOptionPane.showMessageDialog(null, "Q3: "+myDataProtection.getAnswer3()); 
                JOptionPane.showMessageDialog(null, "Q4: "+myDataProtection.getAnswer4());
                JOptionPane.showMessageDialog(null, "Overall Score: "+myDataProtection.getScore());
                navBtn.setVisible(false);
            }
    }//GEN-LAST:event_navBtnActionPerformed

    private void jRadioButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataProtectionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataProtectionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataProtectionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataProtectionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataProtectionGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRadios;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JButton navBtn;
    // End of variables declaration//GEN-END:variables
}
