/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dataprotectionapp;
import javax.swing.JOptionPane;
//import java.awt.event.WindowEvent;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;


/**
 *
 * @author Conor Rooney x16360663, Tony Clabby x16411702
 */
public class LoginGUI extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public LoginGUI() {
        initComponents();

  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLblUsername = new javax.swing.JLabel();
        jLblAge = new javax.swing.JLabel();
        jtxtAge = new javax.swing.JTextField();
        jtxtName = new javax.swing.JTextField();
        jbtnLogin = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jbtnAdmin = new javax.swing.JButton();
        jbtnAdminLogin = new javax.swing.JButton();
        jLblAdminPass = new javax.swing.JLabel();
        jPassAdmin = new javax.swing.JPasswordField();
        jbtnUserLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 30));

        jLblUsername.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLblUsername.setText("Username");

        jLblAge.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLblAge.setText("Age");

        jtxtAge.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jtxtAge.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jtxtName.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jtxtName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jbtnLogin.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jbtnLogin.setText("User");
        jbtnLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jbtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLoginActionPerformed(evt);
            }
        });

        jbtnExit.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });

        jbtnAdmin.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jbtnAdmin.setText("Admin");
        jbtnAdmin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jbtnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAdminActionPerformed(evt);
            }
        });

        jbtnAdminLogin.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jbtnAdminLogin.setText("Admin Login");
        jbtnAdminLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jbtnAdminLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAdminLoginActionPerformed(evt);
            }
        });

        jLblAdminPass.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLblAdminPass.setText("Admin Password");

        jPassAdmin.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jPassAdmin.setText("jPasswordField1");
        jPassAdmin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPassAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPassAdminActionPerformed(evt);
            }
        });

        jbtnUserLogin.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jbtnUserLogin.setText("User Login");
        jbtnUserLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jbtnUserLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUserLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLblUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLblAge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLblAdminPass)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jbtnLogin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnAdmin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)))
                .addGap(349, 349, 349)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnAdminLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtxtName)
                    .addComponent(jPassAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(jtxtAge)
                    .addComponent(jbtnUserLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(64, 64, 64))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnExit)
                .addGap(468, 468, 468))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblUsername)
                    .addComponent(jtxtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblAdminPass)
                    .addComponent(jPassAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblAge)
                    .addComponent(jtxtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnLogin)
                    .addComponent(jbtnUserLogin))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnAdminLogin)
                    .addComponent(jbtnAdmin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jbtnExit)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 72)); // NOI18N
        jLabel1.setText("Login");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(463, 463, 463)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLoginActionPerformed
        jLblUsername.setVisible(true);
        jtxtName.setVisible(true);
        jLblAdminPass.setVisible(false);
        jPassAdmin.setVisible(false);
        jLblAge.setVisible(true);
        jtxtAge.setVisible(true);
        jbtnLogin.setVisible(true);
        jbtnUserLogin.setVisible(true);
        jbtnAdminLogin.setVisible(false);
        jbtnAdmin.setVisible(false);
        jbtnExit.setVisible(true);
    }//GEN-LAST:event_jbtnLoginActionPerformed

    private void jbtnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAdminActionPerformed
        jLblUsername.setVisible(false);
        jtxtName.setVisible(false);
        jLblAdminPass.setVisible(true);
        jPassAdmin.setVisible(true);
        jLblAge.setVisible(false);
        jtxtAge.setVisible(false);
        jbtnLogin.setVisible(false);
        jbtnUserLogin.setVisible(false);
        jbtnAdminLogin.setVisible(true);
        jbtnAdmin.setVisible(true);
        jbtnExit.setVisible(true);
    }//GEN-LAST:event_jbtnAdminActionPerformed

    private void jbtnAdminLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAdminLoginActionPerformed
     String pass = jPassAdmin.getText();
     
     
     //Allows admin to access results page
     if (pass.contains("Admin")){
         jPassAdmin.setText(null);
         setVisible(false);
         AdminResultsGUI myAdminResultsGUI = new AdminResultsGUI();
         myAdminResultsGUI.setVisible(true);
     }
           
        
        
    
    }//GEN-LAST:event_jbtnAdminLoginActionPerformed
                            

    private void jbtnUserLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUserLoginActionPerformed
     File outFile;
     FileWriter fw;
     BufferedWriter bw;
        
     String name = jtxtName.getText();
     String age = jtxtAge.getText();
     
     //Checks for name and age
     if (age.contains("") && (name.contains(""))){
         jtxtName.setText(null);
         jtxtAge.setText(null);
         
         
        //Writes name and age to text file 
        try{
        outFile = new File("Answers.txt");
        fw = new FileWriter(outFile, true);
        bw = new BufferedWriter(fw);
        
        //Write to the file
        bw.write(name);
        bw.newLine();
        bw.write(age);
        bw.newLine();
        bw.newLine();
        
        //Close the stream
        bw.close();
        }
        catch(IOException e){
            JOptionPane.showMessageDialog(null, "Error writing the file.");
        }
         
        //Allows user access to the information page
        setVisible(false);
        DataProtectionGUI myWelcomePageGUI = new DataProtectionGUI();
        myWelcomePageGUI.setVisible(true);
     }
    }//GEN-LAST:event_jbtnUserLoginActionPerformed

    
    private void jPassAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPassAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPassAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLblAdminPass;
    private javax.swing.JLabel jLblAge;
    private javax.swing.JLabel jLblUsername;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPassAdmin;
    private javax.swing.JButton jbtnAdmin;
    private javax.swing.JButton jbtnAdminLogin;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnLogin;
    private javax.swing.JButton jbtnUserLogin;
    private javax.swing.JTextField jtxtAge;
    private javax.swing.JTextField jtxtName;
    // End of variables declaration//GEN-END:variables

        //private void systemExit()
       // {
       ///     
       //    WindowEvent winCloseing = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
      //     
      //  }            


}